import type { Product } from "@/lib/supabase/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    slug: "zapatilla-urbana-negra",
    name: "Zapatilla Urbana Negra",
    description:
      "Diseñada para quienes no se detienen. La Zapatilla Urbana Negra combina una silueta limpia con materiales de primera selección, pensada para moverse con propósito por la ciudad.\n\nSu suela de goma de alta densidad absorbe el impacto en cada paso, mientras el interior de espuma memory foam se adapta a la forma de tu pie desde el primer uso.\n\nDisponible en tallas del 38 al 43. Fabricada con cuero vegano certificado y cordones de algodón orgánico.",
    price: 49990,
    compare_at_price: 79990,
    cost_price: null,
    stock: 8,
    images: ["https://picsum.photos/400/400?random=1"],
    category: "Arena para gatos",
    tags: ["urbano", "negro", "lifestyle"],
    variants: { Talla: ["38", "39", "40", "41", "42", "43"], Color: ["Negro", "Gris carbón"] },
    has_variants: false,
    options: null,
    meta_title: "Zapatilla Urbana Negra | TheGate",
    meta_desc: "Diseñada para el ritmo de la ciudad. Cuero vegano, memory foam, envío gratis.",
    active: true,
    created_at: "2026-04-01T10:00:00Z",
    updated_at: "2026-04-01T10:00:00Z",
  },
  {
    id: "prod-2",
    slug: "polera-oversize-blanca",
    name: "Polera Oversize Blanca",
    description:
      "El básico que nunca falla. Corte oversize pensado para capas o para usar solo, con una caída perfecta que funciona en cualquier contexto.\n\nTela 100% algodón peinado de 220g. Costura reforzada en hombros. Etiqueta bordada en el pecho, sin estampados que se borren con el tiempo.",
    price: 22990,
    compare_at_price: null,
    cost_price: null,
    stock: 3,
    images: ["https://picsum.photos/400/400?random=2"],
    category: "Alimentación y snacks",
    tags: ["básico", "blanco", "oversize"],
    variants: { Talla: ["S", "M", "L", "XL", "XXL"] },
    has_variants: false,
    options: null,
    meta_title: "Polera Oversize Blanca | TheGate",
    meta_desc: "El básico perfecto. Algodón 220g, corte oversize, etiqueta bordada.",
    active: true,
    created_at: "2026-04-05T10:00:00Z",
    updated_at: "2026-04-05T10:00:00Z",
  },
  {
    id: "prod-3",
    slug: "gorro-lana-gris",
    name: "Gorro de Lana Gris",
    description:
      "Tejido en lana merino de primera calidad, este gorro mantiene el calor sin perder forma después de lavarlo.\n\nDiseño ribeteado clásico con doble capa en la vuelta. Talla única. Disponible en gris marengo y negro.",
    price: 14990,
    compare_at_price: 24990,
    cost_price: null,
    stock: 15,
    images: ["https://picsum.photos/400/400?random=3"],
    category: "Control de olores",
    tags: ["gorro", "lana", "invierno"],
    variants: { Color: ["Gris marengo", "Negro"] },
    has_variants: false,
    options: null,
    meta_title: "Gorro de Lana Gris | TheGate",
    meta_desc: "Lana merino, doble capa, talla única. El complemento perfecto para el invierno.",
    active: true,
    created_at: "2026-04-08T10:00:00Z",
    updated_at: "2026-04-08T10:00:00Z",
  },
  {
    id: "prod-4",
    slug: "mochila-urbana-negra",
    name: "Mochila Urbana 20L",
    description:
      "20 litros de capacidad organizada en compartimentos pensados para el día a día: portátil hasta 15\", bolsillo frontal con organizador, bolsillos laterales para botella.\n\nMaterial exterior: nylon ripstop resistente al agua. Tirantes ergonómicos acolchados. Cierre YKK en todos los compartimentos.",
    price: 59990,
    compare_at_price: null,
    cost_price: null,
    stock: 12,
    images: ["https://picsum.photos/400/400?random=4"],
    category: "Limpieza y accesorios",
    tags: ["mochila", "urbano", "laptop"],
    variants: null,
    has_variants: false,
    options: null,
    meta_title: "Mochila Urbana 20L | TheGate",
    meta_desc: "20L, nylon ripstop, portátil 15\". Organización total para el día a día.",
    active: true,
    created_at: "2026-04-10T10:00:00Z",
    updated_at: "2026-04-10T10:00:00Z",
  },
  {
    id: "prod-5",
    slug: "cinturon-cuero-marron",
    name: "Cinturón de Cuero Café",
    description:
      "Cuero vacuno de curtido vegetal, 35mm de ancho, hebilla de bronce envejecido. Con el uso se ablanda y toma la forma de quien lo lleva.\n\nDisponible en tallas 90, 95, 100 y 105 cm. Fabricado artesanalmente en Santiago.",
    price: 29990,
    compare_at_price: 44990,
    cost_price: null,
    stock: 6,
    images: ["https://picsum.photos/400/400?random=5"],
    category: "Limpieza y accesorios",
    tags: ["cinturón", "cuero", "artesanal"],
    variants: { Talla: ["90 cm", "95 cm", "100 cm", "105 cm"] },
    has_variants: false,
    options: null,
    meta_title: "Cinturón de Cuero Café | TheGate",
    meta_desc: "Cuero vacuno curtido vegetal, hebilla bronce, fabricación artesanal en Santiago.",
    active: true,
    created_at: "2026-04-12T10:00:00Z",
    updated_at: "2026-04-12T10:00:00Z",
  },
  {
    id: "prod-6",
    slug: "jeans-slim-negro",
    name: "Jeans Slim Negro",
    description:
      "Corte slim contemporáneo con tiro medio. Denim elástico de 12oz que no pierde la forma y permite total libertad de movimiento.\n\nDetalle de costura interna en blanco. Botón y remaches de cobre. Lavado oscuro uniforme.",
    price: 39990,
    compare_at_price: null,
    cost_price: null,
    stock: 0,
    images: ["https://picsum.photos/400/400?random=6"],
    category: "Packs ahorro",
    tags: ["jeans", "negro", "slim"],
    variants: { Talla: ["28", "30", "32", "34", "36"] },
    has_variants: false,
    options: null,
    meta_title: "Jeans Slim Negro | TheGate",
    meta_desc: "Denim elástico 12oz, corte slim, tiro medio. Disponible en tallas 28–36.",
    active: true,
    created_at: "2026-04-15T10:00:00Z",
    updated_at: "2026-04-15T10:00:00Z",
  },
  {
    id: "prod-7",
    slug: "parka-impermeable-negra",
    name: "Parka Impermeable",
    description:
      "Construida para el invierno chileno. Exterior de nylon ripstop con membrana impermeable de 10.000mm. Relleno de plumón sintético de alta densidad que retiene el calor incluso húmedo.\n\nCapucha removible con visera estructurada. Bolsillos con cierre impermeables. Puños ajustables. Disponible en negro y verde musgo.",
    price: 89990,
    compare_at_price: 129990,
    cost_price: null,
    stock: 5,
    images: ["https://picsum.photos/400/400?random=7"],
    category: "Areneros",
    tags: ["parka", "impermeable", "invierno"],
    variants: { Talla: ["S", "M", "L", "XL"], Color: ["Negro", "Verde musgo"] },
    has_variants: false,
    options: null,
    meta_title: "Parka Impermeable | TheGate",
    meta_desc: "Nylon ripstop, 10.000mm de impermeabilidad, plumón sintético. Para el invierno real.",
    active: true,
    created_at: "2026-04-18T10:00:00Z",
    updated_at: "2026-04-18T10:00:00Z",
  },
  {
    id: "prod-8",
    slug: "sneakers-retro-blancas",
    name: "Sneakers Retro Blancas",
    description:
      "Inspiradas en el calzado deportivo de los 80, reinterpretadas con materiales contemporáneos. Capellada de cuero genuino con refuerzos en gamuza. Plantilla de espuma EVA de alta densidad.\n\nSuela vulcanizada de goma natural. Cordones de algodón orgánico incluidos en dos colores. Disponible en tallas 36 al 44.",
    price: 64990,
    compare_at_price: null,
    cost_price: null,
    stock: 10,
    images: ["https://picsum.photos/400/400?random=8"],
    category: "Packs ahorro",
    tags: ["sneakers", "retro", "blanco"],
    variants: { Talla: ["36", "37", "38", "39", "40", "41", "42", "43", "44"] },
    has_variants: false,
    options: null,
    meta_title: "Sneakers Retro Blancas | TheGate",
    meta_desc: "Cuero genuino, suela vulcanizada, cordones orgánicos. El clásico que nunca falla.",
    active: true,
    created_at: "2026-04-20T10:00:00Z",
    updated_at: "2026-04-20T10:00:00Z",
  },
];

export const MOCK_CATEGORIES = Array.from(new Set(MOCK_PRODUCTS.map((p) => p.category).filter(Boolean))) as string[];

export function getMockProduct(slug: string): Product | null {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) ?? MOCK_PRODUCTS[0];
}
